// ... other imports ...
import net.minecraft.server.level.ServerPlayer;
// ... other code ...

public class PlayerDataCollector {
    // ... other code ...

    public JsonObject collectData() {
        // ... other code ...
        for (ServerPlayer player : players) {
            // ... other code ...
            JsonObject status = new JsonObject();
            // ... other code ...
            // Connection info
            status.addProperty("ping", player.connection.latency);
            status.addProperty("ip_address", player.connection.getRemoteAddress().toString());
            // ... rest of the code ...
        }
        // ... rest of the code ...
    }
}
