modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/AkumasCoffin/mc-panel/issues"

[[mods]]
modId="mcpanel"
version="1.0.0"
displayName="MC Panel Data Collector"
credits="Created for MC Panel web interface"
authors="AkumasCoffin"
displayURL="https://github.com/AkumasCoffin/mc-panel"
description='''
Server-side data collection mod for MC Panel web interface.
Collects comprehensive server metrics, player data, world state, and performance information.
Provides REST API endpoints for real-time server monitoring.

This mod is designed with crash-safe fallback mechanisms and will work even
if full Forge integration is not available.
'''

# Dependencies made optional to prevent crashes
[[dependencies.mcpanel]]
    modId="forge"
    mandatory=false
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcpanel]]
    modId="minecraft"
    mandatory=false
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"